# Generated by Django 4.2.4 on 2023-08-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_support', '0006_ticket_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('ticket',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('user',), 'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
