# Generated by Django 4.2.4 on 2023-08-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_support', '0007_alter_message_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('frozen', 'Frozen')], default='open', max_length=7),
        ),
    ]
